chapter1.Rmd, chapter2.Rmd, chapter3.Rmd, chapter4.Rmd, chapter5.Rmd, chapter6.Rmd
Hey Nick,
Here's my pull request. I've cleaned up the spelling/typos and made it easier to read. 
I haven't added any new SCTs (as outlined in the Evernote doc). I could give those a shot if you'd like.
Jeff
=> Pull Request

chapter1.Rmd, chapter2.Rmd, chapter3.Rmd, chapter5.Rmd, chapter6.Rmd, course.yml
@filipsch , Added a few SCTs with @ncarchedi, would you mind double checking them?
=> Added SCTs for Intro R

chapter2.Rmd
Just updating some minor typos, no major revisions.
=> minor typos

chapter4.Rmd
Factor chapter, ex 1: separate message for undefined vs wrong (https://v.usetapes.com/k7NuWUSF6b), highlight error if object test fails.
Factor chapter, ex 7: clarify that we expect a vector with 5 entries (https://v.usetapes.com/fEcCXxxeFg)
Factor chapter, ex 4 could use highlighting, but I commented out my attempts at changes and left notes.
=> Mc exp custom

chapter4.Rmd
Specify that there should be 5 entries in vector. Addresses #15
=> Mc exp custom instructions

chapter5.Rmd
I believe there is a typo in the error message. It should say `order()` instead of `sort().
=> sort -> order

chapter3.Rmd
Replaced `all_wars_matrix` with `ticket_prices_matrix`
=> Correct variable name in the error message

chapter1.Rmd, chapter2.Rmd, chapter3.Rmd, chapter4.Rmd, chapter5.Rmd, chapter6.Rmd
Purpose of this PR is to convert all the syntax to the new format
It would be wise to test it once again on the `new-format` branch before merging.
(We did test it several times, however another set of eyes would be welcomed)
=> New authoring format

chapter4.Rmd
Fixes typo in Ch4Ex4. See https://github.com/datacamp/courses-intro-to-r/issues/33
=> ch4ex4 fix typo

chapter4.Rmd
Factor levels changed from slow/fast/insane to slow/medium/fast.
=> don't say "insane"

chapter5.Rmd
=> Fix typos in assignment text

chapter5.Rmd
Fixes https://github.com/datacamp/courses-intro-to-r/issues/44
=> fix typo in ch5ex7

chapter3.Rmd
I'm no expert on Yoda grammar but I think the intention was to Yoda-fy "You shall analyze matrices" rather than "You shall analyzing matrices"
=> Fix a minor grammatical mistake

chapter6.Rmd
Typo reported in the exercise in issue #51.
=> fix typo ex6.2

chapter2.Rmd, course.yml
In preparation for an upcoming growth experiment, we'd like to remove the "free" language from descriptions in this course.
=> Remove "free" language for growth experiment

chapter1.Rmd, chapter2.Rmd, chapter3.Rmd, chapter4.Rmd, chapter5.Rmd, chapter6.Rmd
close https://github.com/datacamp/content-bugs/issues/163
=> Alex fix typo

chapter3.Rmd
=> 3.4 fix oops

chapter1.Rmd, chapter2.Rmd, chapter3.Rmd, chapter4.Rmd, chapter5.Rmd, chapter6.Rmd, course.yml
Let's merge Alex's fixes into the mobile branch to have them live
=> Mobile fixes

chapter1.Rmd
Blank commit to trigger a build on `mobile` branch, which was formerly blocked due to the course being free.
=> blank commit

chapter1.Rmd, chapter5.Rmd
=> 5.4 fix broken links

chapter4.Rmd, chapter5.Rmd, chapter6.Rmd, course.yml
Updated base image and updated outdated PEC files and SCTs.
=> Update base image

course.yml
=> Update course descrip

course.yml
=> Update course details from editor

course.yml
=> Update logged-in course description to correct length

chapter2.Rmd, chapter5.Rmd
=> formatting

chapter3.Rmd
=> removed an extra character.

chapter1.Rmd, chapter2.Rmd, chapter3.Rmd, chapter4.Rmd, chapter5.Rmd, chapter6.Rmd
Introduction to R:
1. Remove external links from code blocks
2. Remove syntax like ‘on the right’
3. Remove ‘[s3.amazonaws.com/'](http://s3.amazonaws.com/') from links
=> Mobile Optimization - Remove mobile branch

chapter2.Rmd
=> context edit for 2.5 and 2.12

chapter1.Rmd, chapter2.Rmd, chapter4.Rmd, chapter6.Rmd
See detailed changes [here](https://docs.google.com/spreadsheets/d/1NijWznhaV8SKSJNfI8wEfbSsSQzx40xhkbXxzxcMe0U/edit?gid=2112509870#gid=2112509870).
=> Translations maintenance
